-- =====================================================================
-- THE WARDROBE — seed data (your existing ~103 pieces)
-- HOW TO USE:
--  1. Sign up in the app first (creates your user).
--  2. In Supabase: SQL Editor, run:  select id, email from auth.users;
--  3. Copy your user id, paste it below replacing YOUR_USER_ID_HERE.
--  4. Run this whole file.
-- =====================================================================

-- Replace this value, then run:
\set uid 'YOUR_USER_ID_HERE'

insert into public.items (user_id, name, brand, color, material, notes, tags) values
  (:'uid', 'Sky Blue Tailored Smart Fit Shirt', 'Uniworth', 'Sky Blue', 'Cotton Blend', 'Double cuff, requires cufflinks', ARRAY['formal shirt']::text[]),
  (:'uid', 'White Tailored Smart Fit Shirt', 'Uniworth', 'White', 'Cotton Blend', '', ARRAY['formal shirt']::text[]),
  (:'uid', 'White Tailored Smart Fit Shirt', 'Uniworth', 'White', 'Cotton Blend', '', ARRAY['formal shirt']::text[]),
  (:'uid', 'Off-White Tailored Smart Fit Shirt', 'Uniworth', 'Off-White', 'Cotton Blend', '', ARRAY['formal shirt']::text[]),
  (:'uid', 'Off-White Tailored Smart Fit Shirt', 'Uniworth', 'Off-White', 'Cotton Blend', '', ARRAY['formal shirt']::text[]),
  (:'uid', 'Charcoal Smart Fit Shirt', 'Uniworth', 'Charcoal', 'Polyester Blend', 'Slight slub texture', ARRAY['formal shirt']::text[]),
  (:'uid', 'Dark Navy Formal Shirt', 'Uniworth', 'Dark Navy', 'Cotton Blend', 'Structured', ARRAY['formal shirt']::text[]),
  (:'uid', 'Black Formal Shirt', 'Uniworth', 'Black', 'Cotton Blend', 'Structured', ARRAY['formal shirt']::text[]),
  (:'uid', 'White Linen Shirt', 'Beige', 'White', 'Linen', 'Plain', ARRAY['casual shirt','linen']::text[]),
  (:'uid', 'Beige Linen Shirt', 'Beige', 'Beige', 'Linen', 'Slub texture', ARRAY['casual shirt','linen']::text[]),
  (:'uid', 'Black Linen Shirt', 'Beige', 'Black', 'Linen', 'Plain', ARRAY['casual shirt','linen']::text[]),
  (:'uid', 'White Band Collar Full Sleeve Shirt', 'Outfitters', 'White', 'Cotton Blend', 'Band collar, full sleeves', ARRAY['casual shirt']::text[]),
  (:'uid', 'Navy Band Collar Full Sleeve Shirt', 'Outfitters', 'Navy', 'Cotton Blend', 'Band collar, full sleeves', ARRAY['casual shirt']::text[]),
  (:'uid', 'Powder Pink Italian Linen Shirt', 'Foberry', 'Powder Pink', 'Premium Italian Linen', 'Button-down collar', ARRAY['casual shirt','linen']::text[]),
  (:'uid', 'Baby Blue Italian Linen Shirt', 'Foberry', 'Baby Blue', 'Premium Italian Linen', 'Button-down collar', ARRAY['casual shirt','linen']::text[]),
  (:'uid', 'Maroon Linen Shirt', '', 'Maroon', 'Linen', 'Casual button-down', ARRAY['casual shirt','linen']::text[]),
  (:'uid', 'Dark Blue Linen Shirt', '', 'Dark Blue', 'Linen', 'Button-down', ARRAY['casual shirt','linen']::text[]),
  (:'uid', 'White Polo', 'Uniworth', 'White', 'Knit Cotton', 'Half-sleeve', ARRAY['polo']::text[]),
  (:'uid', 'Beige Polo', 'Uniworth', 'Beige', 'Knit Cotton', 'Half-sleeve', ARRAY['polo']::text[]),
  (:'uid', 'Sky Blue Polo', 'Uniworth', 'Sky Blue', 'Knit Cotton', 'Half-sleeve', ARRAY['polo']::text[]),
  (:'uid', 'Light Grey Polo', 'Uniworth', 'Light Grey', 'Knit Cotton', 'Half-sleeve', ARRAY['polo']::text[]),
  (:'uid', 'Drop Needle Henley - Stone', 'Avant Garde', 'Stone / Pale Beige', 'Cotton-Tencel Blend', 'Drop-needle vertical channel knit, three-button placket, collarless, ribbed cuffs', ARRAY['polo','henley']::text[]),
  (:'uid', 'Drop Needle Henley - Tobacco', 'Avant Garde', 'Tobacco / Chocolate Brown', 'Cotton-Tencel Blend', 'Drop-needle vertical ribbing, tonal brown buttons, relaxed Henley neckline', ARRAY['polo','henley']::text[]),
  (:'uid', 'Zig-Zag Knit Polo - Olive', 'Avant Garde', 'Deep Olive Green', 'Cotton-Tencel Blend', 'Zig-zag chevron micro-weave, polo collar, tonal buttons, rib-knit hem', ARRAY['polo']::text[]),
  (:'uid', 'Breton Striped Polo - Navy/White', 'Avant Garde', 'Navy/White Stripe', 'Cotton-Tencel Blend', 'Horizontal Breton stripes, contrast navy collar, ribbed bicep bands', ARRAY['polo']::text[]),
  (:'uid', 'Black Premium T-Shirt', 'Uniworth', 'Black', 'Cotton', 'Premium, date appropriate', ARRAY['t-shirt']::text[]),
  (:'uid', 'Navy Premium T-Shirt', 'Uniworth', 'Navy', 'Cotton', 'Premium', ARRAY['t-shirt']::text[]),
  (:'uid', 'White Premium T-Shirt', 'Uniworth', 'White', 'Cotton', 'Premium', ARRAY['t-shirt']::text[]),
  (:'uid', 'Light Grey Gym Top - Full Sleeve', 'Export Leftovers', 'Light Grey', 'Cotton', 'Full sleeve', ARRAY['gym']::text[]),
  (:'uid', 'Navy Gym Top - Full Sleeve', 'Export Leftovers', 'Navy', 'Cotton', 'Full sleeve', ARRAY['gym']::text[]),
  (:'uid', 'Dark Navy Gym Top - Full Sleeve', 'Export Leftovers', 'Dark Navy', 'Cotton', 'Full sleeve', ARRAY['gym']::text[]),
  (:'uid', 'Black Gym Top - Full Sleeve', 'Export Leftovers', 'Black', 'Cotton', 'Full sleeve', ARRAY['gym']::text[]),
  (:'uid', 'Dark Chocolate Brown Pleated Trousers', 'Asta Aray', 'Chocolate Brown', 'Wool/Poly Blend', 'Single forward pleat', ARRAY['trousers','tailored']::text[]),
  (:'uid', 'Black Pleated Trousers', 'Asta Aray', 'Black', 'Wool/Poly Blend', 'Single forward pleat', ARRAY['trousers','tailored']::text[]),
  (:'uid', 'White Pleated Trousers', 'Asta Aray', 'White', 'Wool/Poly Blend', 'Single forward pleat', ARRAY['trousers','tailored']::text[]),
  (:'uid', 'Navy Pleated Trousers', 'Asta Aray', 'Navy', 'Wool/Poly Blend', 'Single forward pleat', ARRAY['trousers','tailored']::text[]),
  (:'uid', 'Light Olive Linen Trousers', 'Beige', 'Light Olive', 'Pure Linen', '', ARRAY['trousers','linen']::text[]),
  (:'uid', 'Amor Milano Linen Pants', 'Amor', 'Brown/Beige Pinstripe', 'Linen Blend', 'Single forward pleat, horizontal stripe waistband', ARRAY['trousers','linen']::text[]),
  (:'uid', 'Linen Tailored Pants - White', 'Naya Dour', 'White', '100% Linen', 'Straight fit, structured, low rise, belt with loops', ARRAY['trousers','linen','tailored']::text[]),
  (:'uid', 'Linen Tailored Pants - Cream', 'Naya Dour', 'Cream', '100% Linen', 'Straight fit, structured, low rise, belt with loops', ARRAY['trousers','linen','tailored']::text[]),
  (:'uid', 'Linen Tailored Pants - Light Grey', 'Naya Dour', 'Light Grey', '100% Linen', 'Straight fit, structured, low rise, belt with loops', ARRAY['trousers','linen','tailored']::text[]),
  (:'uid', 'Cream Double Reverse Pleated Trousers', '', 'Cream', 'Wool Blend', 'Tailor-made, double reverse pleat', ARRAY['trousers','tailored']::text[]),
  (:'uid', 'Black Smart Casual Trousers', 'Lama', 'Black', 'Cotton Blend', '', ARRAY['trousers','casual']::text[]),
  (:'uid', 'Beige Smart Casual Trousers', 'Lama', 'Beige', 'Cotton Blend', '', ARRAY['trousers','casual']::text[]),
  (:'uid', 'Beige Smart Casual Trousers', 'Lama', 'Beige', 'Cotton Blend', '', ARRAY['trousers','casual']::text[]),
  (:'uid', 'Navy Denim Jeans', 'Cougar', 'Navy', 'Denim', 'Regular fit', ARRAY['jeans']::text[]),
  (:'uid', 'White Denim Jeans', 'Breakout', 'White', 'Denim', 'Regular fit', ARRAY['jeans']::text[]),
  (:'uid', 'Sky Blue Denim Jeans', 'Cougar', 'Sky Blue', 'Denim', 'Regular fit', ARRAY['jeans']::text[]),
  (:'uid', 'Black Cargo Loungewear Trousers', 'Unbranded', 'Black', '100% Cotton', 'Cargo style', ARRAY['loungewear']::text[]),
  (:'uid', 'Brown Cargo Loungewear Trousers', 'Unbranded', 'Brown', '100% Cotton', 'Cargo style', ARRAY['loungewear']::text[]),
  (:'uid', 'Beige Cargo Loungewear Trousers', 'Unbranded', 'Beige', '100% Cotton', 'Cargo style', ARRAY['loungewear']::text[]),
  (:'uid', 'Black Comfortable Loungewear Trousers', 'Lama', 'Black', 'Heavier Cotton Blend', 'Spring/autumn weight', ARRAY['loungewear']::text[]),
  (:'uid', 'Dark Brown Comfortable Loungewear Trousers', 'Lama', 'Dark Brown', 'Heavier Cotton Blend', 'Spring/autumn weight', ARRAY['loungewear']::text[]),
  (:'uid', 'Beige Comfortable Loungewear Trousers', 'Lama', 'Beige', 'Heavier Cotton Blend', 'Spring/autumn weight', ARRAY['loungewear']::text[]),
  (:'uid', 'Light Brown Ultralight Trousers', 'One', 'Light Beige', '100% Lightweight Cotton', 'Almost see-through', ARRAY['loungewear']::text[]),
  (:'uid', 'Light Brown Ultralight Trousers', 'One', 'Light Beige', '100% Lightweight Cotton', 'Almost see-through', ARRAY['loungewear']::text[]),
  (:'uid', 'Taupe Resort Linen Blazer', 'Lama', 'Muted Khaki Tan', 'Linen Blend', 'Unstructured, slub texture, notch lapels, two-button', ARRAY['blazer','linen']::text[]),
  (:'uid', 'Beige Resort Linen Blazer', 'Lama', 'Beige', 'Linen Blend', 'Unstructured, slub texture, notch lapels, two-button', ARRAY['blazer','linen']::text[]),
  (:'uid', 'Ivory Resort Linen Blazer', 'Lama', 'Ivory', 'Linen Blend', 'Unstructured, slub texture, notch lapels, two-button', ARRAY['blazer','linen']::text[]),
  (:'uid', 'Beige Heavier Linen Blazer', 'Beige', 'Beige', 'Linen Blend', 'Slightly structured', ARRAY['blazer','linen']::text[]),
  (:'uid', 'Brown Slub Texture Blazer', 'Beige', 'Brown', 'Linen Blend', 'Fully structured, suit-level, slub texture', ARRAY['blazer','suit']::text[]),
  (:'uid', 'Dark Navy Lightweight Blazer', 'Dynasty', 'Dark Navy', 'Poly-wool', 'Two-button, notch lapels, gold buttons', ARRAY['blazer']::text[]),
  (:'uid', 'Navy Blazer (Heavier)', 'T.M. Lewin', 'Navy', 'Wool Blend', 'Structured, notch lapels, polka dot lining', ARRAY['blazer','suit']::text[]),
  (:'uid', 'White Latha Outfit', 'J.', 'White', '100% Cotton', 'Tailored', ARRAY['traditional']::text[]),
  (:'uid', 'Cream Boski Outfit', 'J.', 'Cream', 'Boski', 'Tailored', ARRAY['traditional']::text[]),
  (:'uid', 'Beige Kurta Shalwar', 'Charcoal', 'Beige', '', 'Band collar', ARRAY['traditional']::text[]),
  (:'uid', 'White Kurta Shalwar', 'Sapphire', 'White', '', 'Band collar', ARRAY['traditional']::text[]),
  (:'uid', 'Black Qameez Shalwar', 'Unbranded', 'Black', '', 'Full set', ARRAY['traditional']::text[]),
  (:'uid', 'Calvin Klein White Sneakers', 'Calvin Klein', 'White', 'Leather/Synthetic', 'Plain white', ARRAY['footwear','sneakers']::text[]),
  (:'uid', 'Black Drivers', 'Leatherpoint', 'Black', 'Leather', 'Plain', ARRAY['footwear']::text[]),
  (:'uid', 'Brown Pebble Leather Drivers', 'Gomila Intersole', 'Brown', 'Pebble Leather', 'Horse bit detail', ARRAY['footwear']::text[]),
  (:'uid', 'Black Oxfords with Brogue', 'Sage', 'Black', 'Leather', 'Brogue design', ARRAY['footwear','formal']::text[]),
  (:'uid', 'Black Oxfords Plain', 'Leatherpoint', 'Black', 'Leather', 'Plain', ARRAY['footwear','formal']::text[]),
  (:'uid', 'Suede Penny Loafers', 'Marc and Jason', 'Dark Brown / Espresso', 'Suede', 'Chocolate/espresso shade', ARRAY['footwear','loafers']::text[]),
  (:'uid', 'Black Chelsea Boots', 'Sage', 'Black', 'Leather', 'Plain', ARRAY['footwear','boots']::text[]),
  (:'uid', 'Shiny Penny Loafers', 'Leatherpoint', 'Dark Brown', 'Leather', 'Shiny finish, gradient', ARRAY['footwear','loafers']::text[]),
  (:'uid', 'Light Sand Suede Loafers', 'Collin Brian', 'Sand', 'Suede', 'Versatile', ARRAY['footwear','loafers']::text[]),
  (:'uid', 'Black Gym Trainers', 'Ndure', 'Black', 'Synthetic', 'Plain', ARRAY['footwear','gym']::text[]),
  (:'uid', 'Black & Grey Gym Trainers', 'McKenzie', 'Black/Grey', 'Synthetic', 'Two-tone', ARRAY['footwear','gym']::text[]),
  (:'uid', 'Pebble Leather Brown Belt', 'Ndure', 'Brown', 'Pebble Leather', 'Silver/chrome buckle', ARRAY['belt']::text[]),
  (:'uid', 'Pebble Leather Black Belt', 'Sage', 'Black', 'Pebble Leather', 'Rusted buckle', ARRAY['belt']::text[]),
  (:'uid', 'Brown Formal Shiny Belt', 'Leatherpoint', 'Brown', 'Leather', 'Silver/chrome buckle', ARRAY['belt']::text[]),
  (:'uid', 'Black Formal Shiny Belt', 'Leatherpoint', 'Black', 'Leather', 'Silver/chrome buckle', ARRAY['belt']::text[]),
  (:'uid', 'Tissot PRX 35mm Quartz', 'Tissot', 'Blue Dial, Silver Case', 'Stainless Steel', '35mm, quartz', ARRAY['watch']::text[]),
  (:'uid', 'Timex Solar Watch', 'Timex', 'Black Dial, Brown Strap', 'Stainless Steel / Eco Leather', '36mm, solar, sapphire crystal, 100m WR', ARRAY['watch']::text[]),
  (:'uid', 'Casio G-Shock Solar', 'Casio', 'Black with Red Accents', 'Resin', 'Solar, radio-controlled, 200m WR', ARRAY['watch']::text[]),
  (:'uid', 'Casio F-91W', 'Casio', 'Black with Gold Accents', 'Resin', 'Yellow-gold LED, 7-year battery', ARRAY['watch']::text[]),
  (:'uid', 'Ray-Ban Clubmaster - Havana/Brown', 'Ray-Ban', 'Havana', 'Acetate/Metal', 'Brown lenses', ARRAY['accessory','sunglasses']::text[]),
  (:'uid', 'Ray-Ban Clubmaster - Black/Green', 'Ray-Ban', 'Black', 'Acetate/Metal', 'Green lenses, gold metal', ARRAY['accessory','sunglasses']::text[]),
  (:'uid', 'Ray-Ban Wayfarer - Green Polarized', 'Ray-Ban', 'Black', 'Acetate', 'Green polarized lenses', ARRAY['accessory','sunglasses']::text[]),
  (:'uid', 'Allah Ring', '', 'Silver', '925 Sterling Silver', 'Allah inscription', ARRAY['accessory','jewellery']::text[]),
  (:'uid', 'Silver Rope Chain', '', 'Silver', '925 Sterling Silver', 'Rope design', ARRAY['accessory','jewellery']::text[]),
  (:'uid', 'Baseball Cap - Off-White', 'Cougar', 'Off-White', '', '', ARRAY['accessory','hat']::text[]),
  (:'uid', 'Baseball Cap - Camouflage', 'Marks and Spencer', 'Camouflage', '', '', ARRAY['accessory','hat']::text[]),
  (:'uid', 'Woollen Fedora Hat', '', 'Mid Grey', 'Wool', 'Handmade', ARRAY['accessory','hat']::text[]),
  (:'uid', 'Brown Hunter Hat', 'Diversity.pk', 'Brown', 'Soft Denim-like Fabric', 'Hunter/outdoors style', ARRAY['accessory','hat']::text[]);
